manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: loogdream
      url-base: https://github.com/logdream
  projects:
    - name: zmk
      remote: ZitaoTech
      revision: bbkeyboards_q10_9983
      import: app/west.yml
  self:
    path: config
